AdminSide/AdminSide/Pages/Admin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class AdminModel : PageModel
    {

        Model.AllProperties allProperties = new Model.AllProperties();

        // public void OnGet()
        // {
        // }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Admin";
            return Page();
        }

        public IActionResult OnPostUpdateCurrentVMStatus()
		{
            allProperties.ChangeStatus();
			return RedirectToPage();
		}
    }
}

AdminSide/AdminSide/Pages/CreateProduct.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class CreateProductModel : PageModel
    {
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Create Product";
            return Page();
        }
        Database.CreateProduct CP = new Database.CreateProduct();

        [BindProperty]
        public string ProductName { get; set; }

        [BindProperty]
        public string URL { get; set; }

        [BindProperty]
        public int Price { get; set; }

        [BindProperty]
        public int Stock { get; set; }

        [BindProperty]
        public int BrandID { get; set; }

        [BindProperty]
        public int TypeID { get; set; }

        public IActionResult OnPostCreateProduct()
        {
            Model.AllProperties.ResultValue = CP.CreatingProduct(ProductName, URL, Price, Stock, BrandID, TypeID);
            return RedirectToPage("/Show_result");
        }
    }
}

AdminSide/AdminSide/Pages/Create_Brand.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class Create_BrandModel : PageModel
    {
        Database.CreateBrand CB = new Database.CreateBrand();
        Show_resultModel SAM = new Show_resultModel();
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Create Brand";
            return Page();
        }

        [BindProperty]
        public string BrandName { get; set; }

        public IActionResult OnPostCreateBrand()
        {
            Model.AllProperties.ResultValue = CB.CreatingBrand(BrandName);
            return RedirectToPage("/Show_result");
        }
    }
}

/*
    hello world i am here+
                       
*/

AdminSide/AdminSide/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AdminSide.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AdminSide/AdminSide/Pages/Index.cshtml.cs
using System.Net.Security;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AdminSide.Pages
{
    public class IndexModel : PageModel
    {
        private readonly Database.Login _login;
        private readonly ILogger<IndexModel> _logger;
        public int LoginResult { get; private set; }

        public IndexModel(ILogger<IndexModel> logger, Database.Login login)
        {
            _logger = logger;
            _login = login;
        }
        public void OnGet()
        {
 
        }

        public IActionResult OnPost(int EmployeeNumber, string username, string password)
        {
            LoginResult = _login.ValidateUser(EmployeeNumber, username, password);

            if (LoginResult == 1) // Successful login
            {
                HttpContext.Session.SetInt32("UserId", LoginResult);
                return RedirectToPage("/Admin");
            }

            return Page();
        }

    }
}

AdminSide/AdminSide/Pages/Information.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AdminSide/AdminSide/Pages/Product_Type.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class Product_TypeModel : PageModel
    {
        Database.CreateProductType CPT = new Database.CreateProductType();
        Show_resultModel SAM = new Show_resultModel();
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Create Product Type";
            return Page();
        }
        [BindProperty]
        public string TypeName { get; set; }

        public IActionResult OnPostCreateProductType()
        {
            Model.AllProperties.ResultValue = CPT.CreatingproductType(TypeName);
            return RedirectToPage("/Show_result");
        }
    }
}

AdminSide/AdminSide/Pages/Show_result.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class Show_resultModel : PageModel
    {
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }

            return Page();
        }
        internal int ReturnValue { get; set; }

        internal void TakeData(int value){
            ReturnValue = value;
        }
    }
}

AdminSide/AdminSide/Pages/createCity.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class createCityModel : PageModel
    {
        Database.CreateCity Cc = new Database.CreateCity();
        Show_resultModel SAM = new Show_resultModel();
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Create City";
            return Page();
        }
        
        [BindProperty]
        public string CityName { get; set; }

        public IActionResult OnPostCreateVendingMachine()
        {
            Model.AllProperties.ResultValue = Cc.CreatingCity(CityName);
            return RedirectToPage("/Show_result");
        }
    }
}

AdminSide/AdminSide/Pages/createVM.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class createVMModel : PageModel
    {
        Database.CreateVendingMachine CVM = new Database.CreateVendingMachine();
        Show_resultModel SAM = new Show_resultModel();
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Create Vending Machine";
            return Page();
        }

        [BindProperty]
        public string CityName { get; set; }

        [BindProperty]
        public string DBName { get; set; }

        public IActionResult OnPostCreateVendingMachine()
        {
            Model.AllProperties.ResultValue = CVM.CreateVM(DBName, CityName);
            return RedirectToPage("/Show_result");
        }
    }
}

AdminSide/AdminSide/Pages/deleteCity.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class deleteCityModel : PageModel
    {
        Database.DeleteCity DC = new Database.DeleteCity();
        Show_resultModel SAM = new Show_resultModel();
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Delete City";
            return Page();
        }

        [BindProperty]
        public string DBName { get; set; }

        public IActionResult OnPostCreateVendingMachine()
        {
            Model.AllProperties.ResultValue = DC.DeletingCity(DBName);
            return RedirectToPage("/Show_result");
        }
    }
}

AdminSide/AdminSide/Pages/deleteVM.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class deleteVMModel : PageModel
    {
        Database.DeleteVendingMachine DVM = new Database.DeleteVendingMachine();
        Show_resultModel SAM = new Show_resultModel();
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Delete Vending Machine";
            return Page();
        }

        [BindProperty]
        public string DBName { get; set; }

        public IActionResult OnPostCreateVendingMachine()
        {
            Model.AllProperties.ResultValue = DVM.DeleteVM(DBName);
            return RedirectToPage("/Show_result");
        }
    }
}

AdminSide/AdminSide/Pages/showAll.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AdminSide.Model;

namespace AdminSide.Pages
{
	public class showAllModel : PageModel
	{
		Database.ShowAllVM VM = new Database.ShowAllVM();
		public Dictionary<string, string> DisplayInfo { get; set; } = new Dictionary<string, string>();

		public Dictionary<string, bool> VMs()
		{
			return VM.GetVendingMachineStatus();
		}

		public void OnGet()
		{

		}

		// public IActionResult OnPostUpdateCurrentVM(string cityName)
		// {
		// 	Model.AllProperties.CityName = cityName;

		// 	Console.WriteLine(Model.AllProperties.CityName);
		// 	return RedirectToPage("/Admin");
		// }

		public IActionResult OnPostUpdateCurrentVM(string ButtonName)
		{
			Console.WriteLine(ButtonName);
			AdminSide.Model.AllProperties.CityName = ButtonName;
			return RedirectToPage("/Admin");
		}

	}
}

AdminSide/AdminSide/Pages/signout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class signoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Sign Out";
            return Page();
        }

        public IActionResult OnGetSignOut()
        {
            HttpContext.Session.Remove("UserId");
            // Alternatively, you could clear the entire session:
            // HttpContext.Session.Clear();

            return RedirectToPage("/Index");
        }
    }
}

AdminSide/AdminSide/Pages/updateBrand.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class updateBrandModel : PageModel
    {
        Database.UpdateBrand UB = new Database.UpdateBrand();
        Show_resultModel SAM = new Show_resultModel();
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Update Brand";
            return Page();
        }
        [BindProperty]
        public string Old_Brand_Name { get; set; }

        [BindProperty]
        public string New_Brand_Name { get; set; }

        public IActionResult OnPostCreateProductType()
        {
            Model.AllProperties.ResultValue = UB.UpdatingBrand(Old_Brand_Name, New_Brand_Name);
            return RedirectToPage("/Show_result");
        }
    }
}

AdminSide/AdminSide/Pages/updateCity.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class updateCityModel : PageModel
    {
        Database.UpdateCity UC = new Database.UpdateCity();
        Show_resultModel SAM = new Show_resultModel();
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Update City Name";
            return Page();
        }

        [BindProperty]
        public string oldCityName { get; set; }

        [BindProperty]
        public string newCityName { get; set; }

        public IActionResult OnPostCreateVendingMachine()
        {
            Model.AllProperties.ResultValue = UC.UpdatingCity(oldCityName, newCityName);
            return RedirectToPage("/Show_result");
        }
    }
}

AdminSide/AdminSide/Pages/updateProduct.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class updateProductModel : PageModel
    {
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Create Product";
            return Page();
        }
        Database.updateProduct UP = new Database.updateProduct();

        [BindProperty]
        public string ProductName { get; set; }

        [BindProperty]
        public string URL { get; set; }

        [BindProperty]
        public int Price { get; set; }

        [BindProperty]
        public int Stock { get; set; }

        [BindProperty]
        public int BrandID { get; set; }

        [BindProperty]
        public int TypeID { get; set; }

        public IActionResult OnPostCreateProduct()
        {
            Model.AllProperties.ResultValue = UP.UpdatingProduct(ProductName, URL, Price, Stock, BrandID, TypeID);
            return RedirectToPage("/Show_result");
        }
    }
}

AdminSide/AdminSide/Pages/updateProduct_Type.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class updateProduct_TypeModel : PageModel
    {
        Database.UpdateProductType UPT = new Database.UpdateProductType();
        Show_resultModel SAM = new Show_resultModel();
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("UserId") != 1)
            {
                return RedirectToPage("/Index");
            }
            Model.AllProperties.CurrentAction = "Update Product Type";
            return Page();
        }
        [BindProperty]
        public string Old_PT { get; set; }

        [BindProperty]
        public string New_PT { get; set; }

        public IActionResult OnPostCreateProductType()
        {
            Model.AllProperties.ResultValue = UPT.UpdatingPT(Old_PT, New_PT);
            return RedirectToPage("/Show_result");
        }
    }
}

AdminSide/AdminSide/Pages/updateVM.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminSide.Pages
{
    public class updateVMModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AdminSide/AdminSide/Pages/Createproduct.cshtml
@page
@model AdminSide.Pages.CreateProductModel
@{

}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <title>Remove City</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/admin.css" rel="stylesheet">
    <link href="/css/updateProduct.css" rel="stylesheet">
</head>

<body>
    <div class="center-wrapper">
        <div class="Create-container">
            <div class="Create-box">

                <h2>Create a Product</h2>

                <p class="Info">Enter the new information on the product you want to Create</p>

                <form method="post" asp-page-handler="CreateProduct" id="first-step" class="visible">

                    <input type="text" style="text-align:center;" value="@AdminSide.Model.AllProperties.CityName" text
                        readonly>

                    <input type="text" style="text-align:center;" name="ProductName" placeholder="Product Name" required/>

                    <input type="text" style="text-align:center;" name="URL" placeholder="URL" required/>

                    <input type="number" style="text-align:center;" name="Stock" placeholder="stock" required/>

                    <input type="number" style="text-align:center;" name="Price" placeholder="Price" required/>

                    <input type="number" style="text-align:center;" name="BrandID" placeholder="Brand ID" required/>

                    <input type="number" style="text-align:center;" name="TypeID" placeholder="Type ID" required/>

                    <button type="submit" style="margin-top: 1vh; height: 5vh;">Done</button>
                </form>
                <button onclick="goBack()" style="margin-top: 1vh; height: 5vh;">Back</button>

                <script>
                    function goBack() {
                        window.history.back(); // Or you can redirect to a specific URL
                    }
                </script>
            </div>
        </div>
    </div>

</body>

</html>

AdminSide/AdminSide/Pages/Information.cshtml
@page
@model PrivacyModel
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

AdminSide/AdminSide/Pages/Product_Type.cshtml
@page
@model AdminSide.Pages.Product_TypeModel
@{
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <title>Create City</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/admin.css" rel="stylesheet">
    <link href="/css/Product_Type.css" rel="stylesheet">
</head>

<body>
    <div class="center-wrapper">
        <div class="Create-container">
            <div class="Create-box">
                <h2>Insert a new Product Type</h2>
                <p class="Info">Enter the Product Type that you want to enter</p>

                <form method="post" asp-page-handler="CreateProductType" class="visible">

                    <input type="text" style="text-align:center;" name="TypeName" placeholder="Product Type" required/>

                    <button type="submit" style="margin-top: 1vh; height: 5vh;">Done</button>
                </form>
                <button onclick="goBack()" style="margin-top: 1vh; height: 5vh;">Back</button>

                <script>
                    function goBack() {
                        window.history.back(); // Or you can redirect to a specific URL
                    }
                </script>
            </div>
        </div>
    </div>
</body>

</html>

AdminSide/AdminSide/Pages/createCity.cshtml
@page
@model AdminSide.Pages.createCityModel
@{
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <title>Create City</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/admin.css" rel="stylesheet">
    <link href="/css/createCity.css" rel="stylesheet">
</head>

<body>
    <div class="center-wrapper">
        <div class="Create-container">
            <div class="Create-box">
                <h2>Create a new city</h2>
                <p class="Info">Enter the Name of the city</p>

                <form method="post" asp-page-handler="CreateVendingMachine" class="visible">

                    <input type="text" style="text-align:center;" name="CityName" placeholder="City Name" required/>

                    <button type="submit" style="margin-top: 1vh; height: 5vh;">Done</button>
                </form>
                <button onclick="goBack()" style="margin-top: 1vh; height: 5vh;">Back</button>

                <script>
                    function goBack() {
                        window.history.back(); // Or you can redirect to a specific URL
                    }
                </script>
            </div>
        </div>
    </div>
</body>

</html>

AdminSide/AdminSide/Pages/deleteCity.cshtml
@page
@model AdminSide.Pages.deleteCityModel
@{
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <title>Create Vending Machine</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/admin.css" rel="stylesheet">
    <link href="/css/createVM.css" rel="stylesheet">
</head>

<body>
    <div class="center-wrapper">
        <div class="Create-container">
            <div class="Create-box">
                <h2>Delete city</h2>
                <p class="Info">Enter the city name which you want to delete</p>

                <form method="post" asp-page-handler="CreateVendingMachine" class="visible">

                    <input type="text" style="text-align:center;" name="DBName" placeholder="Delete City Name" required/>

                    <button type="submit" style="margin-top: 1vh; height: 5vh;">Done</button>
                </form>
                <button onclick="goBack()" style="margin-top: 1vh; height: 5vh;">Back</button>

                <script>
                    function goBack() {
                        window.history.back(); // Or you can redirect to a specific URL
                    }
                </script>

            </div>
        </div>
    </div>
</body>

</html>

AdminSide/AdminSide/Pages/deleteVM.cshtml
@page
@model AdminSide.Pages.deleteVMModel
@{
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <title>Create Vending Machine</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/admin.css" rel="stylesheet">
    <link href="/css/createVM.css" rel="stylesheet">
</head>

<body>
    <div class="center-wrapper">
        <div class="Create-container">
            <div class="Create-box">
                <h2>Create a new Vending Machine</h2>
                <p class="Info">Enter the city name of where the new vending machine should be located</p>

                <form method="post" asp-page-handler="CreateVendingMachine" class="visible">

                    <input type="text" style="text-align:center;" name="DBName" placeholder="Vending Machine name" required/>

                    <button type="submit" style="margin-top: 1vh; height: 5vh;">Done</button>
                </form>
                <button onclick="goBack()" style="margin-top: 1vh; height: 5vh;">Back</button>

                <script>
                    function goBack() {
                        window.history.back(); // Or you can redirect to a specific URL
                    }
                </script>

            </div>
        </div>
    </div>
</body>

</html>

AdminSide/AdminSide/Pages/showAll.cshtml
@page "/showAll"
@model AdminSide.Pages.showAllModel
@{
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link href="/css/checkbox.css" rel="stylesheet">
<link href="/css/showAll.css" rel="stylesheet" />

<div class="card-container">
    @foreach (var item in Model.VMs())
    {
        var backgroundColor = item.Value ? "green" : "red";
        var statusText = item.Value ? "ONLINE" : "OFFLINE";

        <form method="post" asp-page-handler="UpdateCurrentVM">
            <input type="hidden" name="ButtonName" value="@item.Key" />
            <input type="hidden" name="ButtonStatus" value="@(item.Value ? 1 : 0)" />
            <button type="submit" class="card-button">
                <div class="card">
                    <img src="/Images/showAll.png" alt="Image Description">
                    <div class="card-text">
                        <h1>@item.Key</h1>
                        <h3>Is Vending Machine Operational</h3>
                        <div style="background-color:@backgroundColor; padding:10px; border-radius: 20px; border: 3px solid black;">
                            <span>@statusText</span>
                        </div>
                    </div>
                </div>
            </button>
        </form>
    }
</div>

AdminSide/AdminSide/Pages/signout.cshtml
@page
@model signoutModel
@{
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <title>Create Vending Machine</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="/css/admin.css" rel="stylesheet"> 
    <link href="/css/createVM.css" rel="stylesheet">
</head>

<body>
    <div class="center-wrapper">
        <div class="Create-container">
            <div class="Create-box">
                <h2>Are you sure you want to sign out?</h2>

                    <div class="d-flex">

                        <a asp-page="/Admin" style="width:50%;">

                            <button type="submit" style="margin-top: 1vh; height: 5vh;">Back</button>

                        </a>

                        <div style="margin: 5px;"></div>
                        <a asp-page="/signout" asp-page-handler="SignOut" style="width:50%;">
                            <button type="submit" style="margin-top: 1vh; height: 5vh;">Yes</button>
                        </a>

                    </div>
            </div>
        </div>
    </div>
</body>

</html>